### PR TITLE
Spectrum flagger branch

### PR DESCRIPTION
**Pull request by Carifio24**
This PR contains the spectrum flagger branch, which is specifically for our internal use to check spectra. Pretty much everything except the spectrum viewer has been stripped out. The spectrum viewer will cycle through unchecked galaxies.

As each spectrum appears, one can mark it as "good" or "bad" using the two buttons. These two buttons will send requests that directly update the `spec_is_good` and `spec_is_bad` fields in the galaxy table of the database. When you mark a galaxy, the next one will pop up. If you make a mistake, you can use the arrow buttons to go back and fix it.

This branch is pulling galaxies from a different endpoint than the regular app  (`/hubbles_law/unchecked-galaxies` rather than `hubbles_law/galaxies`). Thus, if you close the app and re-open it, galaxies that have already been checked won't appear in the list.

### CODE REVIEW

**Comment by heywooddogwood** [comment]
Doing a round of spectrum flagging now. Will post message when I stop.

**Comment by heywooddogwood** [comment]
Finished for now.

Ending galaxy:
Spec-1321-52764-0148

Everything after Spec-1321-52764-0148 has the same spectrum??

**Comment by Carifio24** [comment]
Hmm, I'll take a look and see what's up with that

**Comment by Carifio24** [comment]
@heywooddogwood So when I start up this branch, spec-1321-52764-0148 is the second galaxy I see in the list (the first is spec-1316-52790-0095). However, I am seeing different spectra for each galaxy - if you load up this branch again, does the same thing happen?

**Comment by patudom** [comment]
Closing this branch now that we are done with spectrum flagging. Leaving the branch undeleted, though, in case we need to revisit any of this content later.

**Pull request closed without merging**
