### PR TITLE
Update demo to not read states

### PR DESCRIPTION
**Pull request by johnarban**
This PR fixes https://github.com/cosmicds/hubbleds/issues/659, preventing the reading and global, local, and component states from the database. This is a companion to https://github.com/cosmicds/hubbleds/pull/665, and https://github.com/cosmicds/hubbleds/pull/671

### CODE REVIEW

**Comment by patudom** [comment]
I updated this to merge to the public-demo branch instead of main. Is it helpful to also have these on main?

**Comment by patudom** [comment]
Per team call, the plan is to not use a demo branch, so we don't have to maintain 2 separate branches. Instead, we will set up an environment variable that determines whether we turn the retrieval off/on.

**Review by Carifio24 — APPROVED** [review]

**Comment by patudom** [comment]
@johnarban and @Carifio24, should we set up the environment variable before we merge this to main?

**Comment by Carifio24** [comment]
I actually think the piece to read an environment variable needs to be added (unless I missed it somewhere).

**Comment by johnarban** [comment]
This has been merged with main, and now uses the ` CDS_DISABLE_DB` variable to set the value of GlobalState.update_db, by checking that the environment variable exists and has a value of `true`. @Carifio24 @nmearl

**Pull request merged**
