### PR TITLE
Use `expected_size` field to set class size in app

### PR DESCRIPTION
**Pull request by Carifio24**
This PR updates the app to use the teacher-set "expected size" for the class, rather than the number of students currently in the class.

### CODE REVIEW

**Comment by patudom** [comment]
@Carifio24, do we need to have some sort of fallback if the teacher did not enter an expected class size?

**Comment by Carifio24** [comment]
@patudom We probably do want a fallback, yeah. It could be the "actual" class size (that is, how many students are associated with the class in the database).

**Comment by patudom** [comment]
Yeah, that makes sense - can we do what we would have done before, which I think was to count the class size at the beginning of Stage 5?

**Comment by patudom** [comment]
@Carifio24 & I just discussed this - we don't think that we use the class size anywhere as a state variable. (We do keep track of class size on the db side). Jon will confirm - if that's the case, we can close this PR.

**Comment by Carifio24** [comment]
Yeah, I don't think we're actually using this at all - we set this value in a couple of places, but we never read it. We can reopen if we ever do need to update how we determine the size.

**Pull request closed without merging**
